export function init(elem) {
    elem.focus();

    // Auto-resize whenever the user types or if the value is set programmatically
    elem.addEventListener('input', () => resizeToFit(elem));
    afterPropertyWritten(elem, 'value', () => resizeToFit(elem));

    // Auto-submit the form on 'enter' keypress
    elem.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            elem.dispatchEvent(new CustomEvent('change', { bubbles: true }));
            elem.closest('form').dispatchEvent(new CustomEvent('submit', { bubbles: true, cancelable: true }));
        }
    });
}

function resizeToFit(elem) {
    const lineHeight = parseFloat(getComputedStyle(elem).lineHeight);

    elem.rows = 1;
    const numLines = Math.ceil(elem.scrollHeight / lineHeight);
    elem.rows = Math.min(5, Math.max(1, numLines));
}

function afterPropertyWritten(target, propName, callback) {
    const descriptor = getPropertyDescriptor(target, propName);
    Object.defineProperty(target, propName, {
        get: function () {
            return descriptor.get.apply(this, arguments);
        },
        set: function () {
            const result = descriptor.set.apply(this, arguments);
            callback();
            return result;
        }
    });
}

function getPropertyDescriptor(target, propertyName) {
    return Object.getOwnPropertyDescriptor(target, propertyName)
        || getPropertyDescriptor(Object.getPrototypeOf(target), propertyName);
}

// SIG // Begin signature block
// SIG // MIIpPwYJKoZIhvcNAQcCoIIpMDCCKSwCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // GfIRFZ6pOI3Uwod47vBdH/d1hXXSEGElRxfNVzonJqOg
// SIG // gg30MIIGcjCCBFqgAwIBAgITMwAABKuvOsiCTkhVXQAA
// SIG // AAAEqzANBgkqhkiG9w0BAQwFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI1MDkxODE3NTg1N1oX
// SIG // DTI2MDcwNjE3NTg1N1owYzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjENMAsGA1UEAxMELk5FVDCCAaIwDQYJKoZIhvcNAQEB
// SIG // BQADggGPADCCAYoCggGBAKQ4X+4WJICq9ogp+93S3ign
// SIG // Qhx+0SjWT/ZIdwwhDFj10Yfczf2kmMk593Z6IR+5G1Fb
// SIG // PQKk9YHI8vxLyK9K89H7AmPzyxu1tZnS5gqoD70m3sZA
// SIG // OI43mWo1H3KebvYI/abH6XZWAOekiOSx7yMEvA1LX3ge
// SIG // mWEaV0Otsd43VuWRRgmTjyFhiKHThv218roy1mTBbUXw
// SIG // 2gq6o3BcVsr8IalHQSS1U7v534eysUqzI11WlC0+ncUF
// SIG // 9r2ej0mdX61gLWSNZCKNdZ/mXXPMEhz2Q07iwdpAy6O6
// SIG // HNrASQnwfTRVnCn+TY/+E3BoBpUCV7Dg2UMTYJQlAsw7
// SIG // mEaaWSSW3a+S8aFC9unWFY0dNeRox6xl3vjTbzOMpXyr
// SIG // H+/0MDHGqaEO4vSbkIFLyVv6yxqOCtp/k0OcVcu20mBd
// SIG // cKQLKkK37CfjPg82u/8DT0cenCptF0BKVfahZ7lVah5Q
// SIG // lhOmDilG1KEelL+S/TXuj/tEp/MhgGWyvXi9VpwcmcET
// SIG // FSwUlwIDAQABo4IBgjCCAX4wHwYDVR0lBBgwFgYKKwYB
// SIG // BAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0OBBYEFLT595W9
// SIG // tJwzkjCnj1BmAzR7cFJvMFQGA1UdEQRNMEukSTBHMS0w
// SIG // KwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRp
// SIG // b25zIExpbWl0ZWQxFjAUBgNVBAUTDTQ2NDIyMys1MDYw
// SIG // OTAwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggrBgEFBQcB
// SIG // AQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNVHRMBAf8E
// SIG // AjAAMA0GCSqGSIb3DQEBDAUAA4ICAQAHYavo22iKWwSP
// SIG // Fqby97naAenHdlPya5n7g4LWyZURPwKJebBcYN5Ye/Om
// SIG // bkqpGYU9mwFZw6mdkhtP9voNSGhoAq1gsSasS9ni3832
// SIG // F5MP//pfk/vKkluVSti72uM3fqJnD/L/+Fnxg4blQIP4
// SIG // n83zfdSaUm3N1+4SMVsiMXcwbVnJ5xTWSn4bjCEljcfd
// SIG // 66JWujAWUVmjv4CG0SDO7ycJVuYfsY0iQbrkTRPepX1S
// SIG // TCuC3Hl+AYjWeUydM3YdH6G00PJPNOnPjKQdeSqbMXpp
// SIG // U3J3YQ1quEpoEaw6iQ/WDTrJTh4dwqS0mNWgu+nwSgFH
// SIG // EgHhQziOtPsqtatiDcfSAX8ScmimhOBPEUT/8OMP4llp
// SIG // gvUXQBa7cv3Uli4DS5vRbn3hyIFFQ2DyGSD5eRQI8T7q
// SIG // jC9DAX84zq2Q/dgw8Z6x2m9528a/1IeG4B2YEHIdOjMP
// SIG // cvF3fcZ8ocPo9Ek4VojynTBPN2NNBB66/dzysj5Ozg/P
// SIG // upGwvl2zhYDEqQtz1z7qQGyrMor7ce4yeiZoX7atCMX8
// SIG // GH94BhuFKx8q4mogSMzW1UINWMoRX/5rqKxZy4LUHnf/
// SIG // TAfcKhp+RUljdmkhqvtEb/DkyW/p/UunbuIjKXDjaDGP
// SIG // yqs51MNZ0H70DWM8yWf18sUjgsZaWC4hmTEmQcOU6le8
// SIG // CJVNG7jRZDCCB3owggVioAMCAQICCmEOkNIAAAAAAAMw
// SIG // DQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRp
// SIG // ZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTExMDcwODIw
// SIG // NTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0IENvZGUg
// SIG // U2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6qghBNNLry
// SIG // tlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vGEtgL8DjC
// SIG // mQawyDnVARQxQtOJDXlkh36UYCRsr55JnOloXtLfm1Oy
// SIG // CizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv56sIUM+z
// SIG // RLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5kNXimoGMP
// SIG // LdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vjK1oQH01W
// SIG // KKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd6IlPhBry
// SIG // oS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKdgCz1TlaR
// SIG // ITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBSv4yUh7zA
// SIG // IXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbsYR9q4ShJ
// SIG // nV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43BdD1FGd7P4
// SIG // AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhEfEXkwcNy
// SIG // euBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xbn6/83bBm
// SIG // 4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7IvhNdXnFy/
// SIG // dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMvdJX3bvh4
// SIG // IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY0uDWiIwL
// SIG // AgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEEAwIBADAd
// SIG // BgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1ApUwGQYJ
// SIG // KwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQD
// SIG // AgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
// SIG // ci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBP
// SIG // oE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3Br
// SIG // aS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0MjAxMV8y
// SIG // MDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAwTgYI
// SIG // KwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAxMV8yMDEx
// SIG // XzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGRBgkrBgEE
// SIG // AYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9wcmltYXJ5
// SIG // Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBMAGUAZwBh
// SIG // AGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQAZQBtAGUA
// SIG // bgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEAZ/KGpZjg
// SIG // VHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVfLiw++MNy
// SIG // 0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQfYtGUFXY
// SIG // DJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XUtR13lDni
// SIG // 6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELukqQUMm+1o
// SIG // +mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr3vw70L01
// SIG // 724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/DMhji8MUt
// SIG // zluetEk5CsYKwsatruWy2dsViFFFWDgycScaf7H0J/je
// SIG // LDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNNZgvAs031
// SIG // 4Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf2vP48hah
// SIG // mifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+YWG18NzG
// SIG // GwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOXpQlLSBCZ
// SIG // gB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r+0cjgPWe
// SIG // +L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6/IvrC4Dq
// SIG // aTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4ETIheu9B
// SIG // CrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBIa/15n8G9
// SIG // bW1qyVJzEw16UM0xghqjMIIanwIBATCBlTB+MQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
// SIG // Q29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAEq686yIJO
// SIG // SFVdAAAAAASrMA0GCWCGSAFlAwQCAQUAoIGuMBkGCSqG
// SIG // SIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
// SIG // AQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEi
// SIG // BCBUYdb2w68QI5bZ81TaEACeiRT3Mreq9IvxyZ/4datj
// SIG // 0jBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBpAGMAcgBv
// SIG // AHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tMA0GCSqGSIb3DQEBAQUABIIBgEAhNT5LxzwW2SwY
// SIG // F1L+V9y6F1juyEaAovsCAPBl1//Nfhivww6WYTbKKLXv
// SIG // pZboASJf+zU91uN6du1G+AMaFYixIFdKhR8GDW5sWo+u
// SIG // LvZwdOMfGJvgTw0WJr+2TUGUb1dIlChtlxhEoJmB5nKi
// SIG // Rt7IrGXEoG4fTZz9PoTwouAmfh8sxkgbqOtwy14A7+9W
// SIG // 9VwiGdpDYEoAwbVWF8aOLC5+QIWIDAI+ka+kmsVUyj5s
// SIG // PjCm+kJd9aYkdTnFRvHcMoDCcKC+IO2VIfWiZLJAV3bH
// SIG // dEKlqbPnmczhAuvrcZValXI9Lugyy1kvYHXBDMpedQkq
// SIG // FeX+qeWc3RPkH6WA+xuo6wI4X3wJ49ooaznIYOII7SPK
// SIG // /7/4jlM8XSh6KfgXqlg6/n4TgQY9ctn9GLh7nJ7qanpi
// SIG // MjZ97nQCDSeGPJn9VrPRHa2htVDIxW1Szjqfks31Hntw
// SIG // bxRD1yXkRa80oLjSEp+vClGadHtr76tCiXDJ4XBfUivP
// SIG // BluRV3iKB70DLKGCF60wghepBgorBgEEAYI3AwMBMYIX
// SIG // mTCCF5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8wDQYJ
// SIG // YIZIAWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkE
// SIG // ggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
// SIG // AwQCAQUABCCpvScPIun1lsOkPud+lGQMA0dPJpVLqnEl
// SIG // MVLKw11kXQIGaXSsM075GBMyMDI2MDIxMDA2MzEyNy4y
// SIG // NzVaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBP
// SIG // cGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGll
// SIG // bGQgVFNTIEVTTjo2NTFBLTA1RTAtRDk0NzElMCMGA1UE
// SIG // AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
// SIG // EfswggcoMIIFEKADAgECAhMzAAACFRgD04EHJnxTAAEA
// SIG // AAIVMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwMB4XDTI1MDgxNDE4NDgyMFoXDTI2
// SIG // MTExMzE4NDgyMFowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // LTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
// SIG // dGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBU
// SIG // U1MgRVNOOjY1MUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxN
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw3HV3hVx
// SIG // L0lEYPV03XeNKZ517VIbgexhlDPdpXwDS0BYtxPwi4XY
// SIG // pZR1ld0u6cr2Xjuugdg50DUx5WHL0QhY2d9vkJSk02rE
// SIG // /75hcKt91m2Ih287QRxRMmFu3BF6466k8qp5uXtfe6uc
// SIG // iq49YaS8p+dzv3uTarD4hQ8UT7La95pOJiRqxxd0qOGL
// SIG // ECvHLEXPXioNSx9pyhzhm6lt7ezLxJeFVYtxShkavPoZ
// SIG // N0dOCiYeh4KgoKoyagzMuSiLCiMUW4Ue4Qsm658FJNGT
// SIG // Nh7V5qXYVA6k5xjw5WeWdKOz0i9A5jBcbY9fVOo/cA8i
// SIG // 1bytzcDTxb3nctcly8/OYeNstkab/Isq3Cxe1vq96fIH
// SIG // E1+ZGmJjka1sodwqPycVp/2tb+BjulPL5D6rgUXTPF84
// SIG // U82RLKHV57bB8fHRpgnjcWBQuXPgVeSXpERWimt0NF2l
// SIG // COLzqgrvS/vYqde5Ln9YlKKhAZ/xDE0TLIIr6+I/2JTt
// SIG // XP34nfjTENVqMBISWcakIxAwGb3RB5yHCxynIFNVLcfK
// SIG // AsEdC5U2em0fAvmVv0sonqnv17cuaYi2eCLWhoK1Ic85
// SIG // Dw7s/lhcXrBpY4n/Rl5l3wHzs4vOIhu87DIy5QUaEupE
// SIG // syY0NWqgI4BWl6v1wgse+l8DWFeUXofhUuCgVTuTHN3K
// SIG // 8idoMbn8Q3edUIECAwEAAaOCAUkwggFFMB0GA1UdDgQW
// SIG // BBSJIXfxcqAwFqGj9jdwQtdSqadj1zAfBgNVHSMEGDAW
// SIG // gBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBW
// SIG // MFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
// SIG // cGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1w
// SIG // JTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEE
// SIG // YDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUy
// SIG // MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAM
// SIG // BgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
// SIG // BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEAd42HtV+kGbvxzLBTC5O7vkCIBPy/BwpjCzeL
// SIG // 53hAiEOebp+VdNnwm9GVCfYq3KMfrj4UvKQTUAaS5Zkw
// SIG // e1gvZ3ljSSnCOyS5OwNu9dpg3ww+QW2eOcSLkyVAWFrL
// SIG // n6Iig3TC/zWMvVhqXtdFhG2KJ1lSbN222csY3E3/BrGl
// SIG // uAlvET9gmxVyyxNy59/7JF5zIGcJibydxs94JL1BtPgX
// SIG // JOfZzQ+/3iTc6eDtmaWT6DKdnJocp8wkXKWPIsBEfkD6
// SIG // k1Qitwvt0mHrORah75SjecOKt4oWayVLkPTho12e0ong
// SIG // Eg1cje5fxSZGthrMrWKvI4R7HEC7k8maH9ePA3ViH0CV
// SIG // SSOefaPTGMzIhHCo5p3jG5SMcyO3eA9uEaYQJITJlLG3
// SIG // BwwGmypY7C/8/nj1SOhgx1HgJ0ywOJL9xfP4AOcWmCfb
// SIG // sqgGbCaC7WH5sINdzfMar8V7YNFqkbCGUKhc8GpIyE+M
// SIG // KnyVn33jsuaGAlNRg7dVRUSoYLJxvUsw9GOwyBpBwbE9
// SIG // sqOLm+HsO00oF23PMio7WFXcFTZAjp3ujihBAfLrXICg
// SIG // GOHPdkZ042u1LZqOcnlr3XzvgMe+mPPyasW8f0rtzJj3
// SIG // V5E/EKiyQlPxj9Mfq2x9himnlXWGZCVPeEBROrNbDYBf
// SIG // azTyLNCOTsRtksOSV3FBtPnpQtLN754wggdxMIIFWaAD
// SIG // AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3
// SIG // DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYD
// SIG // VQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBB
// SIG // dXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0z
// SIG // MDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
// SIG // CgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9Kp
// SIG // bE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5K
// SIG // Wv64NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTz
// SIG // xXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
// SIG // cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
// SIG // 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3K
// SIG // Ni1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3t
// SIG // pK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5Jas
// SIG // AUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ
// SIG // 1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHo
// SIG // vwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz
// SIG // 1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymei
// SIG // XtcodgLiMxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8w
// SIG // dJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFd
// SIG // Etsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94
// SIG // q0W29R6HXtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0w
// SIG // ggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGC
// SIG // NxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1Ud
// SIG // DgQWBBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAE
// SIG // VTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
// SIG // FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYI
// SIG // KwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBD
// SIG // AEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
// SIG // HwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQw
// SIG // VgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
// SIG // Q2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEB
// SIG // BE4wTDBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRf
// SIG // MjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIB
// SIG // AJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEG
// SIG // k5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi
// SIG // 7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce57
// SIG // 32pvvinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OO
// SIG // PcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
// SIG // OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
// SIG // NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3m
// SIG // Sj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSw
// SIG // ethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23K
// SIG // jgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4
// SIG // S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFE
// SIG // fnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+
// SIG // pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/
// SIG // Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7t
// SIG // fqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJt
// SIG // pQUQwXEGahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEwggEB
// SIG // oYHZpIHWMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYD
// SIG // VQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25z
// SIG // IExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // Tjo2NTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAj6eTejbuYE1Ifjbfrt6tXevCUSCggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAO006lwwIhgPMjAyNjAyMDkyMzIx
// SIG // MDBaGA8yMDI2MDIxMDIzMjEwMFowdDA6BgorBgEEAYRZ
// SIG // CgQBMSwwKjAKAgUA7TTqXAIBADAHAgEAAgIuIDAHAgEA
// SIG // AgISqTAKAgUA7TY73AIBADA2BgorBgEEAYRZCgQCMSgw
// SIG // JjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIB
// SIG // AAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCO3TG1aQVI
// SIG // aZ2QLVSbmCZ4Jw8iQ6arzP7hYUo1U96s5yzD/3zKpq7T
// SIG // cRMgSiSsuiXfQbx4ESDu+w27biCsmogZAwf7O+PKQ6y4
// SIG // sk6F7qipQLzOLteG/4YqmHefn8cKmyP574dM6jNhQ9lf
// SIG // W5HajoD+0l8GqIJ0ts71NUBfIFhoUe+KIzPs22WNIRIw
// SIG // 4YHvYgC/11W8KrphwRNDLeOlPaDrewIZ7Xs0Rj1la2qE
// SIG // ajN/tbkDoUYtoUEWu63wv7EkxNv+4CoQBa7RyQjdjezY
// SIG // hnBfntZpdjq4EAg+JPZk/MaDaQmp4/mxmGVt5gpTq5Vg
// SIG // Tz5BENX2gr2/drylyOkx/HAqMYIEDTCCBAkCAQEwgZMw
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAIV
// SIG // GAPTgQcmfFMAAQAAAhUwDQYJYIZIAWUDBAIBBQCgggFK
// SIG // MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkq
// SIG // hkiG9w0BCQQxIgQg36rwY6aJrturvJxE65Vcj/SgalHs
// SIG // klZ/0ctq3d+6Ii0wgfoGCyqGSIb3DQEJEAIvMYHqMIHn
// SIG // MIHkMIG9BCBwEPR2PDrTFLcrtQsKrUi7oz5JNRCF/KRH
// SIG // MihSNe7sijCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwAhMzAAACFRgD04EHJnxTAAEAAAIVMCIE
// SIG // IOrvbp80ia2zOHjtkY0jIxsBiL/qHkDZboO6UoHBix3y
// SIG // MA0GCSqGSIb3DQEBCwUABIICADNSwAOOFa5v5MA9KLkp
// SIG // EOucISAFAqEy+f5oZ5uSKeyVrzS4U94yRCJR1TvMuuKR
// SIG // gKPdPswUgpwC8YQBZNzU1ho06MnLHUc+MeNVzjfMsU2O
// SIG // /AjqifXRLybdHOhnn9XKL1bbpCHXPSHvzlLom++hwKM6
// SIG // JvoXCyN0qSQp8DmsPwQ/rVm6+Pb84CzEjpSCSvany30M
// SIG // 1bdLFpTzhb0mKVRaBiC2m4RAqmYcYfccsM1mL3YTryR6
// SIG // J/GoyhQ6dDWAydrIW/wmpLJgN/Zm8F73pZTIlz8raqxM
// SIG // ClYCp3Cg85DVsfMGBhOrb5TEJOlb8w740H1m9MlAnHbJ
// SIG // GAyjiUVmJLtrUYp+xSP/q9ebBLEKw/Mku6+j3rWYuC1L
// SIG // bbzV0VkrVF+60oSbHdx1d7yKcvvU5sp8yGCmO8DKD0BN
// SIG // QdANWYMffrtVws7hbBXqAA1DJwqG7+yqM28s1QfQL4uH
// SIG // iDbsijJ6d6fKzhIJ9TX3Lt1Vt0qSc9r73Z5lpjnaM9Ua
// SIG // LQwudT/faO9iW9LNSfnkOC3pJ+NizsYXz/kBu55W/DTa
// SIG // O3IeUEIfdYrREZ7aJxF4MR1mpZf/IhijL7MB1i9dOroE
// SIG // xYBQWpPS/Y+VKNQ7nczXYQKpMRfZ+1f3dkFUxcTwrhUs
// SIG // wx5t/8wMs3FfmJ0blj7I7g1vm9U6j0+alxBt957DLIpc
// SIG // BG1E
// SIG // End signature block
