// The following logic provides auto-scroll behavior for the chat messages list.
// If you don't want that behavior, you can simply not load this module.

window.customElements.define('chat-messages', class ChatMessages extends HTMLElement {
    static _isFirstAutoScroll = true;

    connectedCallback() {
        this._observer = new MutationObserver(mutations => this._scheduleAutoScroll(mutations));
        this._observer.observe(this, { childList: true, attributes: true });
    }

    disconnectedCallback() {
        this._observer.disconnect();
    }

    _scheduleAutoScroll(mutations) {
        // Debounce the calls in case multiple DOM updates occur together
        cancelAnimationFrame(this._nextAutoScroll);
        this._nextAutoScroll = requestAnimationFrame(() => {
            const addedUserMessage = mutations.some(m => Array.from(m.addedNodes).some(n => n.parentElement === this && n.classList?.contains('user-message')));
            const elem = this.lastElementChild;
            if (ChatMessages._isFirstAutoScroll || addedUserMessage || this._elemIsNearScrollBoundary(elem, 300)) {
                elem.scrollIntoView({ behavior: ChatMessages._isFirstAutoScroll ? 'instant' : 'smooth' });
                ChatMessages._isFirstAutoScroll = false;
            }
        });
    }

    _elemIsNearScrollBoundary(elem, threshold) {
        const maxScrollPos = document.body.scrollHeight - window.innerHeight;
        const remainingScrollDistance = maxScrollPos - window.scrollY;
        return remainingScrollDistance < elem.offsetHeight + threshold;
    }
});

// SIG // Begin signature block
// SIG // MIIpQgYJKoZIhvcNAQcCoIIpMzCCKS8CAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // QcS6CJjCBbSnVWfEuBHKlPNK89AvLArmIwVSnmBZwV6g
// SIG // gg30MIIGcjCCBFqgAwIBAgITMwAABKuvOsiCTkhVXQAA
// SIG // AAAEqzANBgkqhkiG9w0BAQwFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI1MDkxODE3NTg1N1oX
// SIG // DTI2MDcwNjE3NTg1N1owYzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjENMAsGA1UEAxMELk5FVDCCAaIwDQYJKoZIhvcNAQEB
// SIG // BQADggGPADCCAYoCggGBAKQ4X+4WJICq9ogp+93S3ign
// SIG // Qhx+0SjWT/ZIdwwhDFj10Yfczf2kmMk593Z6IR+5G1Fb
// SIG // PQKk9YHI8vxLyK9K89H7AmPzyxu1tZnS5gqoD70m3sZA
// SIG // OI43mWo1H3KebvYI/abH6XZWAOekiOSx7yMEvA1LX3ge
// SIG // mWEaV0Otsd43VuWRRgmTjyFhiKHThv218roy1mTBbUXw
// SIG // 2gq6o3BcVsr8IalHQSS1U7v534eysUqzI11WlC0+ncUF
// SIG // 9r2ej0mdX61gLWSNZCKNdZ/mXXPMEhz2Q07iwdpAy6O6
// SIG // HNrASQnwfTRVnCn+TY/+E3BoBpUCV7Dg2UMTYJQlAsw7
// SIG // mEaaWSSW3a+S8aFC9unWFY0dNeRox6xl3vjTbzOMpXyr
// SIG // H+/0MDHGqaEO4vSbkIFLyVv6yxqOCtp/k0OcVcu20mBd
// SIG // cKQLKkK37CfjPg82u/8DT0cenCptF0BKVfahZ7lVah5Q
// SIG // lhOmDilG1KEelL+S/TXuj/tEp/MhgGWyvXi9VpwcmcET
// SIG // FSwUlwIDAQABo4IBgjCCAX4wHwYDVR0lBBgwFgYKKwYB
// SIG // BAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0OBBYEFLT595W9
// SIG // tJwzkjCnj1BmAzR7cFJvMFQGA1UdEQRNMEukSTBHMS0w
// SIG // KwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRp
// SIG // b25zIExpbWl0ZWQxFjAUBgNVBAUTDTQ2NDIyMys1MDYw
// SIG // OTAwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggrBgEFBQcB
// SIG // AQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljQ29kU2ln
// SIG // UENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNVHRMBAf8E
// SIG // AjAAMA0GCSqGSIb3DQEBDAUAA4ICAQAHYavo22iKWwSP
// SIG // Fqby97naAenHdlPya5n7g4LWyZURPwKJebBcYN5Ye/Om
// SIG // bkqpGYU9mwFZw6mdkhtP9voNSGhoAq1gsSasS9ni3832
// SIG // F5MP//pfk/vKkluVSti72uM3fqJnD/L/+Fnxg4blQIP4
// SIG // n83zfdSaUm3N1+4SMVsiMXcwbVnJ5xTWSn4bjCEljcfd
// SIG // 66JWujAWUVmjv4CG0SDO7ycJVuYfsY0iQbrkTRPepX1S
// SIG // TCuC3Hl+AYjWeUydM3YdH6G00PJPNOnPjKQdeSqbMXpp
// SIG // U3J3YQ1quEpoEaw6iQ/WDTrJTh4dwqS0mNWgu+nwSgFH
// SIG // EgHhQziOtPsqtatiDcfSAX8ScmimhOBPEUT/8OMP4llp
// SIG // gvUXQBa7cv3Uli4DS5vRbn3hyIFFQ2DyGSD5eRQI8T7q
// SIG // jC9DAX84zq2Q/dgw8Z6x2m9528a/1IeG4B2YEHIdOjMP
// SIG // cvF3fcZ8ocPo9Ek4VojynTBPN2NNBB66/dzysj5Ozg/P
// SIG // upGwvl2zhYDEqQtz1z7qQGyrMor7ce4yeiZoX7atCMX8
// SIG // GH94BhuFKx8q4mogSMzW1UINWMoRX/5rqKxZy4LUHnf/
// SIG // TAfcKhp+RUljdmkhqvtEb/DkyW/p/UunbuIjKXDjaDGP
// SIG // yqs51MNZ0H70DWM8yWf18sUjgsZaWC4hmTEmQcOU6le8
// SIG // CJVNG7jRZDCCB3owggVioAMCAQICCmEOkNIAAAAAAAMw
// SIG // DQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRp
// SIG // ZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTExMDcwODIw
// SIG // NTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0IENvZGUg
// SIG // U2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6qghBNNLry
// SIG // tlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vGEtgL8DjC
// SIG // mQawyDnVARQxQtOJDXlkh36UYCRsr55JnOloXtLfm1Oy
// SIG // CizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv56sIUM+z
// SIG // RLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5kNXimoGMP
// SIG // LdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vjK1oQH01W
// SIG // KKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd6IlPhBry
// SIG // oS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKdgCz1TlaR
// SIG // ITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBSv4yUh7zA
// SIG // IXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbsYR9q4ShJ
// SIG // nV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43BdD1FGd7P4
// SIG // AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhEfEXkwcNy
// SIG // euBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xbn6/83bBm
// SIG // 4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7IvhNdXnFy/
// SIG // dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMvdJX3bvh4
// SIG // IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY0uDWiIwL
// SIG // AgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEEAwIBADAd
// SIG // BgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1ApUwGQYJ
// SIG // KwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQD
// SIG // AgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
// SIG // ci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBP
// SIG // oE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3Br
// SIG // aS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0MjAxMV8y
// SIG // MDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAwTgYI
// SIG // KwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAxMV8yMDEx
// SIG // XzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGRBgkrBgEE
// SIG // AYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9wcmltYXJ5
// SIG // Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBMAGUAZwBh
// SIG // AGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQAZQBtAGUA
// SIG // bgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEAZ/KGpZjg
// SIG // VHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVfLiw++MNy
// SIG // 0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQfYtGUFXY
// SIG // DJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XUtR13lDni
// SIG // 6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELukqQUMm+1o
// SIG // +mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr3vw70L01
// SIG // 724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/DMhji8MUt
// SIG // zluetEk5CsYKwsatruWy2dsViFFFWDgycScaf7H0J/je
// SIG // LDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNNZgvAs031
// SIG // 4Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf2vP48hah
// SIG // mifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+YWG18NzG
// SIG // GwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOXpQlLSBCZ
// SIG // gB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r+0cjgPWe
// SIG // +L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6/IvrC4Dq
// SIG // aTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4ETIheu9B
// SIG // CrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBIa/15n8G9
// SIG // bW1qyVJzEw16UM0xghqmMIIaogIBATCBlTB+MQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
// SIG // Q29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAEq686yIJO
// SIG // SFVdAAAAAASrMA0GCWCGSAFlAwQCAQUAoIGuMBkGCSqG
// SIG // SIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcC
// SIG // AQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEi
// SIG // BCBh+AaUHVAXW0wrjv1q3klBla+AgicLust56QjVkdMX
// SIG // 3TBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBpAGMAcgBv
// SIG // AHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tMA0GCSqGSIb3DQEBAQUABIIBgECE1apTjaCIvVxl
// SIG // icYCJQUiN11QGVJfTph+Au2JAvs6d10BuWwOIstoHgLU
// SIG // P8MlqfUlktCA0qLfNbN1QZFtT1CihWTz1kf0jJ1hXGEm
// SIG // uQEhbmdTpXftRULosZo0ZdLTyA56OQkoIkDuU2Flk4h2
// SIG // UW7NNYux23iiTab3oBs3pQPT4dORfshROjwnAch3VyUl
// SIG // xaNO9d/Cz06A6o64br9avU7cqQ5+UMUWOFQ6r7JDc3gT
// SIG // JXY+uK2iMxG88Pj0/fJ6yAo8dn+STCGfFMjpCKF9+E9w
// SIG // wvYV3Qc9TYqsCwbe4w6zEyMwFbr5rCsWTzjtFg6rmFyD
// SIG // StVYJ0daaleQW3uZy4oWYnpZ0KjwRtVX6qSutyw8S0AF
// SIG // KSj7N1mFyypGtP91UhAMFRd1GEKVlbhxSU5RULJo4MmF
// SIG // wUraOsgXl0wIsczNN0E4c3Dsgwx8Tmm3qwPmsZn0yUwv
// SIG // BbhLGx379G4WxcK5wjuwQrPFGuBzGexpbxWkhIrANWs4
// SIG // jqU2YKN7uTpb66GCF7AwghesBgorBgEEAYI3AwMBMYIX
// SIG // nDCCF5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJ
// SIG // YIZIAWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkE
// SIG // ggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
// SIG // AwQCAQUABCDCxDNtt1I8xVrL9acXmB89Fo2L2nSf7Nya
// SIG // rKD+8NYyVAIGaXS+EwPrGBMyMDI2MDIxMDA2MzEyNi45
// SIG // NjdaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBP
// SIG // cGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGll
// SIG // bGQgVFNTIEVTTjo2RjFBLTA1RTAtRDk0NzElMCMGA1UE
// SIG // AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
// SIG // Ef4wggcoMIIFEKADAgECAhMzAAACHAlVFdfDWQfRAAEA
// SIG // AAIcMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwMB4XDTI1MDgxNDE4NDgzMVoXDTI2
// SIG // MTExMzE4NDgzMVowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // LTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
// SIG // dGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBU
// SIG // U1MgRVNOOjZGMUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxN
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAow0xEAUa
// SIG // FIyyLIXeFzeI8IKyBON2u0Dr02ISE5p9G5CUXfnFu2S0
// SIG // E1gWCMvDWpopX6lRxjmgnqaL3BtnWlBVTo8xUNRZu23i
// SIG // e4YBMAJB7Ut6mnqnHVwvDJxGO4TD3SnrCd+yg35B9QFe
// SIG // jq3o4+OByvXjynaypZyukcQaLsKQvoxE8ElHH7zcOXEJ
// SIG // WmU3rnXzaW/S4SH3OPhoUbTTcy6nUgKx5pRWiQ24UEPL
// SIG // YzcxGJjqjkz+GiCWGPFHDMdW86laWvmCslouQPsN2eBk
// SIG // 8dxJcEZmW4l6p4TthoXcfexEA9YdYaMz10aMhZNpdsNa
// SIG // DtDQUMDEC3k1D1My69MXSPlUmD9xFyDlkXiVa7BCEp3X
// SIG // cVtqTgzHGwr28JD6oE7zEPYeuZOiuCBXTZSo/wk3tbDl
// SIG // sESbIPV6inYqrzxiMYqlxfCdzC3Cimh9/NT/Lk9/aU+I
// SIG // yyc9b3OaT0dZ8wgLaVDCGELRMrqyImdFHv0MudctzW/k
// SIG // PsV3Ja9ufpKWujEiN3CW//X8hFa9j5ImNeQzcMit3MoS
// SIG // aoGwnbiZJX1IyibIphlqccXFk4oTTSOQBsAUw8U0gwOn
// SIG // M5UJD8mBUBd65Np6NBkx2cviJ4I34GyXFCWyy5Ft1QsB
// SIG // YyVfAG3KOhCfPHQf8lQzJvLr57YW0bD/xVs4Ag4gTS6K
// SIG // ZNyFEfX9jFdRlr0CAwEAAaOCAUkwggFFMB0GA1UdDgQW
// SIG // BBRa3mOCzB8u7zpvDh8MGKVYLCk7ZDAfBgNVHSMEGDAW
// SIG // gBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBW
// SIG // MFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
// SIG // cGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1w
// SIG // JTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEE
// SIG // YDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUy
// SIG // MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAM
// SIG // BgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
// SIG // BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEAklb6w/deaid3BujQCtWFBe0n9pkyRy+yyWEg
// SIG // 70iDwoJ5u0e0O+4GerNzdZb1zTPsHJ8EGMyo1K7ytL21
// SIG // +pmdFMTl19PC8OJ5Y2p+XKUQy2dD+hggRMmJgDQsgbOC
// SIG // xHYeO+jg4t+vg61wUrovzzLkH3z0PJXXvoNuBj9Lda9C
// SIG // iNMd60451Kube99ArSf6ZMj3t0p4rFbgSazDs+8TJ+8K
// SIG // A5GVaYjPHj9rlMuI3WjohEc9apnQ6hMjMck3jlHZIwlu
// SIG // VYeUQE0qjmApfMtTAEzbMUdY8sLTunL1GkbDSeKn9O7l
// SIG // lBGnNtyM1uM9Mdv1VyWh0z/IriQKIjntqqGyoF0HvDHO
// SIG // FZCyUDBPLflyiu7Y1zQ/sPounsb96aBfQdq3h3LOn6t+
// SIG // m9EnNz/G6MzzWvpJk6YgTHTIqeQN/F/XpiPvbfek3nq/
// SIG // PYbL3au+kBfRUHiCFXSvt6lor0HC626vUmz9ZNPOxwEW
// SIG // Luccomxsy3JwWH79vsM/7ARqoG5h6d6NahfaOuRP4XI9
// SIG // xtdH3Pa/NCLyQjxKXyLxzwQzjddkX2EpTJnlypuhPmEd
// SIG // ea59Uz2E303LxyXSnKBvGsAnyWYAfnejr3YAiL9YrN2l
// SIG // 2dn198RpA4DCm9QtZYiwC0q2fuUvui34PfPIUZByf7wH
// SIG // uuWu50hY9WLx1kOMI8xyo7AI6TaNrnIwggdxMIIFWaAD
// SIG // AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3
// SIG // DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYD
// SIG // VQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBB
// SIG // dXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0z
// SIG // MDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
// SIG // CgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9Kp
// SIG // bE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5K
// SIG // Wv64NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTz
// SIG // xXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
// SIG // cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
// SIG // 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3K
// SIG // Ni1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3t
// SIG // pK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5Jas
// SIG // AUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ
// SIG // 1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHo
// SIG // vwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz
// SIG // 1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymei
// SIG // XtcodgLiMxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8w
// SIG // dJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFd
// SIG // Etsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94
// SIG // q0W29R6HXtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0w
// SIG // ggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGC
// SIG // NxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1Ud
// SIG // DgQWBBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAE
// SIG // VTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
// SIG // FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYI
// SIG // KwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBD
// SIG // AEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8w
// SIG // HwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQw
// SIG // VgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNy
// SIG // b3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9v
// SIG // Q2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEB
// SIG // BE4wTDBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRf
// SIG // MjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIB
// SIG // AJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEG
// SIG // k5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi
// SIG // 7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce57
// SIG // 32pvvinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OO
// SIG // PcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
// SIG // OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
// SIG // NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3m
// SIG // Sj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSw
// SIG // ethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23K
// SIG // jgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4
// SIG // S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFE
// SIG // fnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+
// SIG // pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/
// SIG // Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7t
// SIG // fqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJt
// SIG // pQUQwXEGahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEB
// SIG // oYHZpIHWMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
// SIG // V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
// SIG // A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYD
// SIG // VQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25z
// SIG // IExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
// SIG // Tjo2RjFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
// SIG // b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsO
// SIG // AwIaAxUAWmTiA01u5mxq/nVxiRJLMOskVGeggYMwgYCk
// SIG // fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
// SIG // aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkq
// SIG // hkiG9w0BAQsFAAIFAO00/DwwIhgPMjAyNjAyMTAwMDM3
// SIG // MTZaGA8yMDI2MDIxMTAwMzcxNlowdzA9BgorBgEEAYRZ
// SIG // CgQBMS8wLTAKAgUA7TT8PAIBADAKAgEAAgIHYwIB/zAH
// SIG // AgEAAgITYjAKAgUA7TZNvAIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQDEhSRW
// SIG // 7+klWgltFopNDjADl5cu5IRYZ1eO7o6gpZj5qckniwzw
// SIG // sV0oYgJrg4C87rPG9X03rt3Q0L1WOU+kYLjq5tlBtCya
// SIG // eWPAHa4BJ64sXPFHVwMmMj0R1ydXi+3kVVZT/NbRR8e2
// SIG // /T1ieVpBP73ayx9wN2FBy7o7QecYto9uEmokBn6vGGqH
// SIG // 2UUyCNcn+kK2XX/U8nXWCjyMz5PnaVHRYIBdiy1szVAB
// SIG // bNVihomdZW2YEazTALM4eHzQ5fXXwEingE9uoGpJEqBm
// SIG // 6nMdRtf0sj+ZM5Ldi94Xi7aCQk+gCY9DmU6d+fTcztYO
// SIG // WSf3bFrATDFqtsKAdcq5Bk8+Z9AEMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAIcCVUV18NZB9EAAQAAAhwwDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQgMMPDHy2wLt+vXvokRuD3u4fX
// SIG // t2LE8eao4M2olrmVv04wgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCCgIGkmNhdo7+KE7dWhI+E2Ctx2RLWo
// SIG // YvvJodCIciHHaDCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAACHAlVFdfDWQfRAAEAAAIc
// SIG // MCIEINT6iSokSLqnBdG7LxIZz1JQnEW+8C3Ik6WLiXYK
// SIG // 2y1zMA0GCSqGSIb3DQEBCwUABIICADTdjinK3XVMtfDj
// SIG // 9JNz+XeTRnXvdWaLAWJKzliKmzxwatWSHD6mwfHzTpp1
// SIG // EalClaDcZ2ghjQCIQc0gVhy8MZVMZGm06RP+JD8rqIeO
// SIG // 4oDiEHcAaEvQH4t4pAh6AibAewUdHlTItQ/6MeIfM5nF
// SIG // Q4rVX4UbrFu+OQv5+Fe6tgrDIsnqYn30FEGioLeHC670
// SIG // Jlq9X2mLj0AScmnG1kzNE474ObdSHxivAWP+sghjqg2K
// SIG // 2DtLzzfMzh3YvVhGWjqLREjVfa9MLTDY/7nKXpuDhPqm
// SIG // 1f8/0l2jZ0JlcB0bPo/05W3Hj2bPbRwH4B2D3G7erTrU
// SIG // OZAjnsnFA1CSpumhjT7YAsb2N4UDFPPxUeb6zBDMlDZg
// SIG // YPFSJZc9mEysV5H1SV5XURQahGfwLWJ+g9hAjDJZO+jJ
// SIG // 7xefnh6pyA3Pai16etkvTv3jRaKp/gQq5eJcCcfqA2Uk
// SIG // oujsofudS8fxo4RE2EHTNyfYQ5u6H+2ZoGcDGDvvL8VI
// SIG // h82Baoyc6NAjt1I9Zhna02bXIpz7CEOuFF5hdEGOGJd/
// SIG // G+cCtI6a2wpvgm199kwXO0FXdZuCpVyHFE7NRwE97SO2
// SIG // c24ZkVoHexo5m8flwgRT0cD4OmlUdMakvO2KhHZwO6fW
// SIG // KjscSs9raRr+nahlkRMRl2CGLMACqUTnu1A9uYaKSZDb
// SIG // Y++MCQ9H
// SIG // End signature block
